# Configuration for GHES instances
ghes_instances:
  - name: 'github'
    api_url: 'https://david-wiggs-060b1459dd3ce046c.qaboot.net/api/v3' 
    auth_var: 'GHES_API_TOKEN_1'  
  - name: 'github'
    api_url: 'https://david-wiggs-070bf9a715effa9de.ghe-test.ninja/api/v3'
    auth_var: 'GHES_API_TOKEN_2'

# GitHub Enterprise Cloud configuration for license management
ghec:
  name: 'avocado-corp'
  api_url: 'https://api.github.com'
  auth_var: 'GH_ENTERPRISE_TOKEN_CLOUD'
