name: GHAS Enablement Workflow

on:
  issues:
    types: [opened]

jobs:
  call-ghas-enablement:
    if: contains(github.event.issue.labels.*.name, 'ghas-enablement')
    permissions:
      issues: write
      contents: read
    uses: oodles-noodles/ghas-issue-ops/.github/workflows/ghas-enablement-action.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
    secrets: inherit
